namespace PordznakanAPI.DTOs
{
    public class MmuhInstitutionSummaryDto
    {
        public Guid DshhSchoolId { get; set; }   // Internal Id (Guid) generated by us
        public int KtakSchoolId { get; set; }    // InstId from external API
        public string Name { get; set; } = string.Empty;
    }
}
