using PordznakanAPI.Models;

public class School
{
    public Guid DshhSchoolId { get; set; }    // ID generated by us
    public int KtakSchoolId { get; set; }  // ID coming from external API (schools_id)
    public int RegionId { get; set; }         // Region ID coming from external API
    public string Name { get; set; } = string.Empty;  // school_name
    public string Marz { get; set; } = string.Empty;  // marz (province)
    public string Region { get; set; } = string.Empty;  // region (district)
    public string Community { get; set; } = string.Empty;  // community
    public string Email { get; set; } = string.Empty;     // school_email
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }

    // Navigation
    public ICollection<Classroom> Classrooms { get; set; } = new List<Classroom>();
}
